import type { Metadata } from 'next';
import { GeistSans } from 'geist/font/sans';

import './globals.css';

// * components
import Header from '@/layout/Header';
import Footer from '@/layout/Footer';
import FluidCursor from '@/components/FluidCursor';

// * config
import { resolveFavicon } from '@/nexd.config';

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
  icons: {
    icon: resolveFavicon(),
  },
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang='en' className={GeistSans.className} suppressHydrationWarning>
      <body>
        <FluidCursor />

        <div className='relative z-20'>
          <Header />
          {children}

          <Footer />
        </div>

        <div id='popup-root' />
      </body>
    </html>
  );
};

export default RootLayout;
