import type { Metadata } from 'next';
import { GeistSans } from 'geist/font/sans';

import './globals.css';

// * components
import Header from '@/layout/Header';
import Footer from '@/layout/Footer';

// * config
import { resolveFavicon } from '@/nexd.config';

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
  icons: {
    icon: resolveFavicon(),
  },
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang='en' className={GeistSans.className} suppressHydrationWarning>
      <body>
        <div className='relative lg:grid lg:grid-cols-[auto_1fr_auto]'>
          <Header />

          {children}
        </div>

        <Footer />

        <div id='popup-root' />
      </body>
    </html>
  );
};

export default RootLayout;
